name: baker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.15.1
  hive_flutter: ^1.1.0
  go_router: ^16.0.0
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  uuid: ^4.2.1
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  signature: ^6.3.0
  image_picker: ^1.0.4
  syncfusion_flutter_pdf: ^30.1.39
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
